try {
  console.lo('try 블록');
} catch (error) {
  console.log('catch 블록');
  console.log('예외가 발생했습니다.');
} finally {
  console.log('finally 블록');
}
